-- LUMA: Create watchlists table
-- Run this in Supabase Dashboard → SQL Editor

-- 1. Create the watchlists table
CREATE TABLE IF NOT EXISTS public.watchlists (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  tmdb_id bigint NOT NULL,
  movie_id bigint,
  title text NOT NULL,
  year integer,
  rating numeric(3,1),
  poster_url text,
  backdrop_path text,
  release_date text,
  vote_average numeric(3,1),
  media_type text NOT NULL DEFAULT 'movie',
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 2. Prevent duplicate movies for the same user
CREATE UNIQUE INDEX IF NOT EXISTS idx_watchlists_user_movie
  ON public.watchlists (user_id, tmdb_id);

-- 3. Index for fast user lookups
CREATE INDEX IF NOT EXISTS idx_watchlists_user_id
  ON public.watchlists (user_id);

-- 4. Enable Row Level Security
ALTER TABLE public.watchlists ENABLE ROW LEVEL SECURITY;

-- 5. RLS Policies
-- Authenticated users can view only their own watchlist
CREATE POLICY "Users can view their own watchlist"
  ON public.watchlists
  FOR SELECT
  USING (auth.uid() = user_id);

-- Authenticated users can insert only their own watchlist
CREATE POLICY "Users can insert their own watchlist"
  ON public.watchlists
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Authenticated users can delete only their own watchlist
CREATE POLICY "Users can delete their own watchlist"
  ON public.watchlists
  FOR DELETE
  USING (auth.uid() = user_id);
